### ISSUE TITLE
Не верные данные в справочнике

### ISSUE THREAD

**Issue by acnapd** [lers-uchet/ImportTemperature#11]
![изображение](https://user-images.githubusercontent.com/33048914/213700718-55cc8cd0-12c2-4e61-b25a-e0ed609262e9.png)
![изображение](https://user-images.githubusercontent.com/33048914/213700742-3533702e-51a7-4684-aaad-1d2dff694a15.png)
![изображение](https://user-images.githubusercontent.com/33048914/213700790-9a6f8455-8be8-4a01-a7f0-81eca60f6992.png)

crontab:
```
0 */3 * * * cd /home/user/tempImport/ImportTemperature && dotnet run --source GisMeteo --incity 162327 --server http://*.*.*.*:10000 --login * --password * --destTerritory "Ленинградская Область, Всеволожский Район, Городской поселок Янино-1" --importDays 2
0 */3 * * * cd /home/user/tempImport/ImportTemperature && dotnet run --source GisMeteo --incity 11424 --server http://*.*.*.*:10000 --login * --password * --destTerritory "Ленинградская Область, Гатчинский Район,  Город Гатчина" --importDays 2
0 */3 * * * cd /home/user/tempImport/ImportTemperature && dotnet run --source GisMeteo --incity 14809 --server http://*.*.*.*:10000 --login * --password * --destTerritory "Санкт-Петербург Город, Город Колпино" --importDays 2
```

Температуры на представленные даты/территории находятся в районе -1 / +1

**Comment by achikhv** [comment]
Тут проблем несколько.

Одна из них - код 14809, который вы используете для загрузки данных для Колпино, принадлежит городу [Поградец, Албания](https://www.gismeteo.ru/diary/14809/2023/1/).

Кроме того, у нас всё-таки есть сбой при чтении среднесуточных температур с дробной частью. Это обсуждалось в вопросе #8.

Сегодня опубликуем версию, где этот сбой исправлен. Плюс, ускорим чтение данных с gismeteo, чтобы на каждые сутки не перечитывались месячные данные. Обновите утилиту и импортируйте данные с заменой существующих.
