### ISSUE TITLE
импорт температуры с gismeteo

### ISSUE THREAD

**Issue by acnapd** [lers-uchet/ImportTemperature#8]
Иногда читает один-два дня, иногда залипает на первом дне.
```
ImportTemperature.exe --source GisMeteo
--incity 4079 --server http://*****:**** --login ****** --password ********* --destTerritory "Санкт-Петербург Город, Город Санкт-Петербург" --importDays
 2 --missingOnly
Чтение среднесуточных температур с сайта.
Считываем температуру за 17.12.22
Ошибка чтение среднесуточных температур. Input string was not in a correct forma
t.

Нажмите любую клавишу для выхода...

```

**Comment by achikhv** [comment]
К сожалению, иногда такие ошибки могут случаться. Например, если сервер гисметео не ответил и вернул страницу с ошибкой. Можно только "обернуть" вызов в скрипт и попытаться вызвать импорт ещё раз если вернулся ненулевой код ответа.

**Comment by acnapd** [comment]
80% итераций читает 1-2 дня, 20% итераций отваливается на первом дне.

**Comment by acnapd** [comment]
Ошибка возникает в случае чтения дробных значений температуры. Челочисленные читаются и записываются исправно.

**Comment by achikhv** [comment]
А разве на странице дневника погоды могут быть дробные значения? Я посмотрел дневник по СПб за 17.12.2022, там только целые.

В любом случае, ошибка теоретически может возникнуть если у вас разделитель целой и дробной части не запятая. Сделал более универсальное преобразование.

**Comment by acnapd** [comment]
когда опубликуете?

**Comment by acnapd** [comment]
> А разве на странице дневника погоды могут быть дробные значения? Я посмотрел дневник по СПб за 17.12.2022, там только целые.
> 
> В любом случае, ошибка теоретически может возникнуть если у вас разделитель целой и дробной части не запятая. Сделал более универсальное преобразование.

если мы получим 2 среза: "1" и "2" градуса, то при расчёте среднего получим 1.5

**Comment by achikhv** [comment]
Уже опубликовано.

Ошибка возникает не при расчёте, а при разборе значения с сайта. Теоретически может возникнуть только если сайт вернул какое-то неверное значение.

Ну и при работе с gismeteo никакие расчёты не делаются. Они нужны только для meteoinfo.
